
spring.application.name=Spring-Security-JWT
spring.app.jwtSecrete = mySecreteKey1234!#765
spring.app.jwtExpirationMs = 40000000000000000000000000000 
# its mandatory to hv the valid time in production
#this could be read from the @Value at the utils class