spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: root
    password: pass123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Use "create", "update", "validate", or "none" based on need
    show-sql: true      # Enables SQL query logging
    open-in-view: false # Prevents LazyInitializationException

  # Hibernate logging (Optional)
  logging:
    level:
      org.hibernate.SQL: DEBUG  # Shows SQL queries
      org.hibernate.type.descriptor.sql: TRACE  # Shows query parameters
